# Generated by Django 2.2.10 on 2021-02-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembersModel',
            fields=[
                ('idno', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('real_name', models.CharField(max_length=50)),
                ('timezone', models.CharField(max_length=50)),
                ('start_time_one', models.DateTimeField()),
                ('end_time_one', models.DateTimeField()),
                ('start_time_two', models.DateTimeField()),
                ('end_time_two', models.DateTimeField()),
                ('start_time_three', models.DateTimeField()),
                ('end_time_three', models.DateTimeField()),
            ],
        ),
    ]
